---
Name: translatabletldroutes
After: cms/routes#modelascontrollerroutes
---
Director:
  rules:
    'Security//$Action/$ID/$OtherID': 'Security'
    'CMSSecurity//$Action/$ID/$OtherID': 'CMSSecurity'
    'dev': 'DevelopmentAdmin'
    'more': 'More'
    'interactive': 'SapphireREPL'
    'InstallerTest//$Action/$ID/$OtherID': 'InstallerTest'
    'JSTestRunner//$Action/$ID/$OtherID': 'JSTestRunner'
    'SapphireInfo//$Action/$ID/$OtherID': 'SapphireInfo'
    'SapphireREPL//$Action/$ID/$OtherID': 'SapphireREPL'
    'admin': 'AdminRootController'
    '': 'TranslatableRootURLController'
    '$URLSegment//$Action/$ID/$OtherID': 'TranslatableModelAsController'
    'StaticExporter//$Action/$ID/$OtherID': 'StaticExporter'
    'RebuildStaticCacheTask//$Action/$ID/$OtherID': 'RebuildStaticCacheTask'
    'RemoveOrphanedPagesTask//$Action/$ID/$OtherID': 'RemoveOrphanedPagesTask'
    'SiteTreeMaintenanceTask//$Action/$ID/$OtherID': 'SiteTreeMaintenanceTask'
    'SiteTreeMaintenanceTask//$Action/$ID/$OtherID': 'SiteTreeMaintenanceTask'